version: "3.8"

services:
  backend:
    build:
      context: ./backend/app
      dockerfile: ../../docker/php/Dockerfile
    volumes:
      - ./backend/app:/var/www/html
    ports:
      - "8000:8000"
    working_dir: /var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000

  frontend:
    build:
      context: ./frontend/app
      dockerfile: ../../docker/node/Dockerfile
    volumes:
      - ./frontend/app:/app
    ports:
      - "5173:5173"
    working_dir: /app
    command: sh -c "npm install && npm run dev"
